services:
  db:
    image: postgres:16
    container_name: ai-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ai_pgdata:/var/lib/postgresql/data
    networks: [backend]

  app:
    build: .
    container_name: ai-text-service
    depends_on: [db]
    restart: unless-stopped
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_APPLICATION_JSON: >
        {
          "management.metrics.enable.process": false,
          "management.metrics.enable.system": false,
          "management.metrics.export.simple.enabled": false
        }
    command: >
      java -Dmanagement.metrics.enable.process=false
           -Dmanagement.metrics.enable.system=false
           -Dmanagement.metrics.export.simple.enabled=false
           -jar /app/app.jar
    ports:
      - "8080:8080"
    networks: [backend]
  



networks:
  backend:

volumes:
  ai_pgdata:
